[tool.poetry]
name = "Cpp"
version = "0.1.0"
description = ""
authors = ["Uy Ha <hchanuy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
jinja2 = "^3.1.2"
conan = "^2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
