cmake_language(CALL message "STATUS;hello")
cmake_language(CALL message "STATUS hello")
cmake_language(CALL message "STATUS" "hello")
cmake_language(CALL message STATUS hello)
cmake_language(CALL message STATUS;hello)
cmake_language(CALL message "STATUS";"hello")
cmake_language(CALL message "STATUS";hello)
